### ISSUE TITLE
Pychron

### ISSUE THREAD

**Issue by juliariccinmgrl** [NMGRL/pychron_web#15]
Trying to open the last FC-2 analyzed on Pychron, I obtained this error (for all of the FC-2):
-- Analysis 28440-01 not in local repository Irradiation-NM-323. You may need to pull changes. If local repository is up to date you may need to push changes from the data collection computer.

This happened only with FC-2 samples of NM-323. The unknown samples work.

**Comment by jirhiker** [comment]
these issue is not related to the PychronWeb project aka SampleTracker
